# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMCXtal_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.FolderN = QtWidgets.QLabel(self.centralwidget)
        self.FolderN.setGeometry(QtCore.QRect(40, 70, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FolderN.setFont(font)
        self.FolderN.setFrameShape(QtWidgets.QFrame.Panel)
        self.FolderN.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FolderN.setText("")
        self.FolderN.setObjectName("FolderN")
        self.FolderUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.FolderUpdate.setGeometry(QtCore.QRect(150, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FolderUpdate.setFont(font)
        self.FolderUpdate.setObjectName("FolderUpdate")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.SampleUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.SampleUpdate.setGeometry(QtCore.QRect(740, 30, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SampleUpdate.setFont(font)
        self.SampleUpdate.setObjectName("SampleUpdate")
        self.SampN = QtWidgets.QLineEdit(self.centralwidget)
        self.SampN.setGeometry(QtCore.QRect(630, 70, 181, 31))
        self.SampN.setObjectName("SampN")
        self.Nu = QtWidgets.QLineEdit(self.centralwidget)
        self.Nu.setGeometry(QtCore.QRect(110, 180, 50, 25))
        self.Nu.setObjectName("Nu")
        self.StpN = QtWidgets.QLineEdit(self.centralwidget)
        self.StpN.setGeometry(QtCore.QRect(310, 180, 50, 25))
        self.StpN.setObjectName("StpN")
        self.Delt = QtWidgets.QLineEdit(self.centralwidget)
        self.Delt.setGeometry(QtCore.QRect(50, 180, 50, 25))
        self.Delt.setObjectName("Delt")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 150, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.KphiEnd = QtWidgets.QLineEdit(self.centralwidget)
        self.KphiEnd.setGeometry(QtCore.QRect(240, 180, 50, 25))
        self.KphiEnd.setObjectName("KphiEnd")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(370, 150, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(70, 120, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 150, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 147, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.KphiStart = QtWidgets.QLineEdit(self.centralwidget)
        self.KphiStart.setGeometry(QtCore.QRect(180, 180, 50, 25))
        self.KphiStart.setObjectName("KphiStart")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 150, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.TimperFrm = QtWidgets.QLineEdit(self.centralwidget)
        self.TimperFrm.setGeometry(QtCore.QRect(370, 180, 50, 25))
        self.TimperFrm.setObjectName("TimperFrm")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 150, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(200, 120, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.Col_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.Col_Btn.setGeometry(QtCore.QRect(480, 160, 141, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Col_Btn.setFont(font)
        self.Col_Btn.setObjectName("Col_Btn")
        self.C3 = QtWidgets.QLineEdit(self.centralwidget)
        self.C3.setGeometry(QtCore.QRect(90, 420, 100, 25))
        self.C3.setObjectName("C3")
        self.Sel6 = QtWidgets.QPushButton(self.centralwidget)
        self.Sel6.setGeometry(QtCore.QRect(400, 540, 75, 25))
        self.Sel6.setObjectName("Sel6")
        self.Mv1 = QtWidgets.QPushButton(self.centralwidget)
        self.Mv1.setGeometry(QtCore.QRect(500, 340, 75, 25))
        self.Mv1.setObjectName("Mv1")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(50, 500, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.LZ2 = QtWidgets.QLineEdit(self.centralwidget)
        self.LZ2.setGeometry(QtCore.QRect(330, 380, 50, 25))
        self.LZ2.setObjectName("LZ2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(50, 340, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.LX4 = QtWidgets.QLineEdit(self.centralwidget)
        self.LX4.setGeometry(QtCore.QRect(210, 460, 50, 25))
        self.LX4.setObjectName("LX4")
        self.LX2 = QtWidgets.QLineEdit(self.centralwidget)
        self.LX2.setGeometry(QtCore.QRect(210, 380, 50, 25))
        self.LX2.setObjectName("LX2")
        self.LZ1 = QtWidgets.QLineEdit(self.centralwidget)
        self.LZ1.setGeometry(QtCore.QRect(330, 340, 50, 25))
        self.LZ1.setObjectName("LZ1")
        self.Sel3 = QtWidgets.QPushButton(self.centralwidget)
        self.Sel3.setGeometry(QtCore.QRect(400, 420, 75, 25))
        self.Sel3.setObjectName("Sel3")
        self.LX6 = QtWidgets.QLineEdit(self.centralwidget)
        self.LX6.setGeometry(QtCore.QRect(210, 540, 50, 25))
        self.LX6.setObjectName("LX6")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(330, 310, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.LX5 = QtWidgets.QLineEdit(self.centralwidget)
        self.LX5.setGeometry(QtCore.QRect(210, 500, 50, 25))
        self.LX5.setObjectName("LX5")
        self.Mv2 = QtWidgets.QPushButton(self.centralwidget)
        self.Mv2.setGeometry(QtCore.QRect(500, 380, 75, 25))
        self.Mv2.setObjectName("Mv2")
        self.LY6 = QtWidgets.QLineEdit(self.centralwidget)
        self.LY6.setGeometry(QtCore.QRect(270, 540, 50, 25))
        self.LY6.setObjectName("LY6")
        self.LY2 = QtWidgets.QLineEdit(self.centralwidget)
        self.LY2.setGeometry(QtCore.QRect(270, 380, 50, 25))
        self.LY2.setObjectName("LY2")
        self.C4 = QtWidgets.QLineEdit(self.centralwidget)
        self.C4.setGeometry(QtCore.QRect(90, 460, 100, 25))
        self.C4.setObjectName("C4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(50, 380, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(235, 280, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.Sel4 = QtWidgets.QPushButton(self.centralwidget)
        self.Sel4.setGeometry(QtCore.QRect(400, 460, 75, 25))
        self.Sel4.setObjectName("Sel4")
        self.LZ5 = QtWidgets.QLineEdit(self.centralwidget)
        self.LZ5.setGeometry(QtCore.QRect(330, 500, 50, 25))
        self.LZ5.setObjectName("LZ5")
        self.C1 = QtWidgets.QLineEdit(self.centralwidget)
        self.C1.setGeometry(QtCore.QRect(90, 340, 100, 25))
        self.C1.setObjectName("C1")
        self.LZ3 = QtWidgets.QLineEdit(self.centralwidget)
        self.LZ3.setGeometry(QtCore.QRect(330, 420, 50, 25))
        self.LZ3.setObjectName("LZ3")
        self.Mv3 = QtWidgets.QPushButton(self.centralwidget)
        self.Mv3.setGeometry(QtCore.QRect(500, 420, 75, 25))
        self.Mv3.setObjectName("Mv3")
        self.C6 = QtWidgets.QLineEdit(self.centralwidget)
        self.C6.setGeometry(QtCore.QRect(90, 540, 100, 25))
        self.C6.setObjectName("C6")
        self.LZ4 = QtWidgets.QLineEdit(self.centralwidget)
        self.LZ4.setGeometry(QtCore.QRect(330, 460, 50, 25))
        self.LZ4.setObjectName("LZ4")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(270, 310, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.Sel5 = QtWidgets.QPushButton(self.centralwidget)
        self.Sel5.setGeometry(QtCore.QRect(400, 500, 75, 25))
        self.Sel5.setObjectName("Sel5")
        self.LY3 = QtWidgets.QLineEdit(self.centralwidget)
        self.LY3.setGeometry(QtCore.QRect(270, 420, 50, 25))
        self.LY3.setObjectName("LY3")
        self.LY4 = QtWidgets.QLineEdit(self.centralwidget)
        self.LY4.setGeometry(QtCore.QRect(270, 460, 50, 25))
        self.LY4.setObjectName("LY4")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(50, 420, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.LX3 = QtWidgets.QLineEdit(self.centralwidget)
        self.LX3.setGeometry(QtCore.QRect(210, 420, 50, 25))
        self.LX3.setObjectName("LX3")
        self.C2 = QtWidgets.QLineEdit(self.centralwidget)
        self.C2.setGeometry(QtCore.QRect(90, 380, 100, 25))
        self.C2.setObjectName("C2")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(90, 290, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.Sel1 = QtWidgets.QPushButton(self.centralwidget)
        self.Sel1.setGeometry(QtCore.QRect(400, 340, 75, 25))
        self.Sel1.setObjectName("Sel1")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(50, 540, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.C5 = QtWidgets.QLineEdit(self.centralwidget)
        self.C5.setGeometry(QtCore.QRect(90, 500, 100, 25))
        self.C5.setObjectName("C5")
        self.Mv4 = QtWidgets.QPushButton(self.centralwidget)
        self.Mv4.setGeometry(QtCore.QRect(500, 460, 75, 25))
        self.Mv4.setObjectName("Mv4")
        self.LZ6 = QtWidgets.QLineEdit(self.centralwidget)
        self.LZ6.setGeometry(QtCore.QRect(330, 540, 50, 25))
        self.LZ6.setObjectName("LZ6")
        self.LX1 = QtWidgets.QLineEdit(self.centralwidget)
        self.LX1.setGeometry(QtCore.QRect(210, 340, 50, 25))
        self.LX1.setObjectName("LX1")
        self.Mv6 = QtWidgets.QPushButton(self.centralwidget)
        self.Mv6.setGeometry(QtCore.QRect(500, 540, 75, 25))
        self.Mv6.setObjectName("Mv6")
        self.LY5 = QtWidgets.QLineEdit(self.centralwidget)
        self.LY5.setGeometry(QtCore.QRect(270, 500, 50, 25))
        self.LY5.setObjectName("LY5")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(50, 460, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(210, 310, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.Sel2 = QtWidgets.QPushButton(self.centralwidget)
        self.Sel2.setGeometry(QtCore.QRect(400, 380, 75, 25))
        self.Sel2.setObjectName("Sel2")
        self.LY1 = QtWidgets.QLineEdit(self.centralwidget)
        self.LY1.setGeometry(QtCore.QRect(270, 340, 50, 25))
        self.LY1.setObjectName("LY1")
        self.Mv5 = QtWidgets.QPushButton(self.centralwidget)
        self.Mv5.setGeometry(QtCore.QRect(500, 500, 75, 25))
        self.Mv5.setObjectName("Mv5")
        self.LogZone = QtWidgets.QScrollArea(self.centralwidget)
        self.LogZone.setGeometry(QtCore.QRect(630, 130, 331, 441))
        self.LogZone.setWidgetResizable(True)
        self.LogZone.setObjectName("LogZone")
        self.LogWidget = QtWidgets.QWidget()
        self.LogWidget.setGeometry(QtCore.QRect(0, 0, 329, 439))
        self.LogWidget.setObjectName("LogWidget")
        self.LogL1 = QtWidgets.QLabel(self.LogWidget)
        self.LogL1.setGeometry(QtCore.QRect(0, 0, 331, 441))
        self.LogL1.setText("")
        self.LogL1.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.LogL1.setObjectName("LogL1")
        self.LogZone.setWidget(self.LogWidget)
        self.warn1 = QtWidgets.QLabel(self.centralwidget)
        self.warn1.setGeometry(QtCore.QRect(50, 210, 46, 21))
        self.warn1.setText("")
        self.warn1.setObjectName("warn1")
        self.warn2 = QtWidgets.QLabel(self.centralwidget)
        self.warn2.setGeometry(QtCore.QRect(110, 210, 46, 21))
        self.warn2.setText("")
        self.warn2.setObjectName("warn2")
        self.warn4 = QtWidgets.QLabel(self.centralwidget)
        self.warn4.setGeometry(QtCore.QRect(240, 210, 46, 21))
        self.warn4.setText("")
        self.warn4.setObjectName("warn4")
        self.warn3 = QtWidgets.QLabel(self.centralwidget)
        self.warn3.setGeometry(QtCore.QRect(180, 210, 46, 21))
        self.warn3.setText("")
        self.warn3.setObjectName("warn3")
        self.warn5 = QtWidgets.QLabel(self.centralwidget)
        self.warn5.setGeometry(QtCore.QRect(310, 210, 46, 21))
        self.warn5.setText("")
        self.warn5.setObjectName("warn5")
        self.warn6 = QtWidgets.QLabel(self.centralwidget)
        self.warn6.setGeometry(QtCore.QRect(370, 210, 46, 21))
        self.warn6.setText("")
        self.warn6.setObjectName("warn6")
        self.Calibration = QtWidgets.QPushButton(self.centralwidget)
        self.Calibration.setGeometry(QtCore.QRect(840, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Calibration.setFont(font)
        self.Calibration.setObjectName("Calibration")
        self.CK1 = QtWidgets.QCheckBox(self.centralwidget)
        self.CK1.setGeometry(QtCore.QRect(590, 340, 21, 21))
        self.CK1.setText("")
        self.CK1.setObjectName("CK1")
        self.CK2 = QtWidgets.QCheckBox(self.centralwidget)
        self.CK2.setGeometry(QtCore.QRect(590, 380, 21, 21))
        self.CK2.setText("")
        self.CK2.setObjectName("CK2")
        self.CK3 = QtWidgets.QCheckBox(self.centralwidget)
        self.CK3.setGeometry(QtCore.QRect(590, 420, 21, 21))
        self.CK3.setText("")
        self.CK3.setObjectName("CK3")
        self.CK4 = QtWidgets.QCheckBox(self.centralwidget)
        self.CK4.setGeometry(QtCore.QRect(590, 460, 21, 21))
        self.CK4.setText("")
        self.CK4.setObjectName("CK4")
        self.CK5 = QtWidgets.QCheckBox(self.centralwidget)
        self.CK5.setGeometry(QtCore.QRect(590, 500, 21, 21))
        self.CK5.setText("")
        self.CK5.setObjectName("CK5")
        self.CK6 = QtWidgets.QCheckBox(self.centralwidget)
        self.CK6.setGeometry(QtCore.QRect(590, 540, 21, 21))
        self.CK6.setText("")
        self.CK6.setObjectName("CK6")
        self.SUMCK = QtWidgets.QCheckBox(self.centralwidget)
        self.SUMCK.setGeometry(QtCore.QRect(440, 180, 16, 21))
        self.SUMCK.setText("")
        self.SUMCK.setObjectName("SUMCK")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 150, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Indi = QtWidgets.QLabel(self.centralwidget)
        self.Indi.setGeometry(QtCore.QRect(500, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Indi.setFont(font)
        self.Indi.setText("")
        self.Indi.setAlignment(QtCore.Qt.AlignCenter)
        self.Indi.setObjectName("Indi")
        self.warn7 = QtWidgets.QLabel(self.centralwidget)
        self.warn7.setGeometry(QtCore.QRect(630, 100, 181, 16))
        self.warn7.setText("")
        self.warn7.setObjectName("warn7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "13BMC Single Crystal Data Collection"))
        self.label.setText(_translate("MainWindow", "Data folder"))
        self.FolderUpdate.setText(_translate("MainWindow", "Update"))
        self.label_3.setText(_translate("MainWindow", "Sample"))
        self.SampleUpdate.setText(_translate("MainWindow", "Update"))
        self.label_6.setText(_translate("MainWindow", "Del"))
        self.label_11.setText(_translate("MainWindow", "Time"))
        self.label_12.setText(_translate("MainWindow", "Detector"))
        self.label_9.setText(_translate("MainWindow", "Start"))
        self.label_10.setText(_translate("MainWindow", "Step#"))
        self.label_8.setText(_translate("MainWindow", "End"))
        self.label_7.setText(_translate("MainWindow", "Nu"))
        self.label_13.setText(_translate("MainWindow", "kphi"))
        self.Col_Btn.setText(_translate("MainWindow", "Collect!"))
        self.Sel6.setText(_translate("MainWindow", "Select"))
        self.Mv1.setText(_translate("MainWindow", "Move"))
        self.label_19.setText(_translate("MainWindow", "C5"))
        self.label_16.setText(_translate("MainWindow", "C1"))
        self.Sel3.setText(_translate("MainWindow", "Select"))
        self.label_24.setText(_translate("MainWindow", "Z"))
        self.Mv2.setText(_translate("MainWindow", "Move"))
        self.label_14.setText(_translate("MainWindow", "C2"))
        self.label_21.setText(_translate("MainWindow", "Sample Position"))
        self.Sel4.setText(_translate("MainWindow", "Select"))
        self.Mv3.setText(_translate("MainWindow", "Move"))
        self.label_23.setText(_translate("MainWindow", "Y"))
        self.Sel5.setText(_translate("MainWindow", "Select"))
        self.label_17.setText(_translate("MainWindow", "C3"))
        self.label_20.setText(_translate("MainWindow", "Sample Description"))
        self.Sel1.setText(_translate("MainWindow", "Select"))
        self.label_18.setText(_translate("MainWindow", "C6"))
        self.Mv4.setText(_translate("MainWindow", "Move"))
        self.Mv6.setText(_translate("MainWindow", "Move"))
        self.label_15.setText(_translate("MainWindow", "C4"))
        self.label_22.setText(_translate("MainWindow", "X"))
        self.Sel2.setText(_translate("MainWindow", "Select"))
        self.Mv5.setText(_translate("MainWindow", "Move"))
        self.Calibration.setText(_translate("MainWindow", "Calibration"))
        self.label_2.setText(_translate("MainWindow", "SUM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
