# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GridScan_main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 626)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.WinPath = QtWidgets.QLabel(self.centralwidget)
        self.WinPath.setGeometry(QtCore.QRect(120, 60, 730, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WinPath.setFont(font)
        self.WinPath.setText("")
        self.WinPath.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.WinPath.setObjectName("WinPath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.LinPath = QtWidgets.QLineEdit(self.centralwidget)
        self.LinPath.setGeometry(QtCore.QRect(120, 20, 650, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LinPath.setFont(font)
        self.LinPath.setObjectName("LinPath")
        self.Hmotor = QtWidgets.QLineEdit(self.centralwidget)
        self.Hmotor.setGeometry(QtCore.QRect(100, 230, 100, 30))
        self.Hmotor.setObjectName("Hmotor")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 230, 60, 30))
        self.label.setObjectName("label")
        self.Vmotor = QtWidgets.QLineEdit(self.centralwidget)
        self.Vmotor.setGeometry(QtCore.QRect(100, 270, 100, 30))
        self.Vmotor.setObjectName("Vmotor")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 60, 30))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 270, 60, 30))
        self.label_5.setObjectName("label_5")
        self.Vstart = QtWidgets.QLineEdit(self.centralwidget)
        self.Vstart.setGeometry(QtCore.QRect(300, 270, 100, 30))
        self.Vstart.setObjectName("Vstart")
        self.Hstart = QtWidgets.QLineEdit(self.centralwidget)
        self.Hstart.setGeometry(QtCore.QRect(300, 230, 100, 30))
        self.Hstart.setObjectName("Hstart")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 230, 60, 30))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 270, 60, 30))
        self.label_7.setObjectName("label_7")
        self.Vend = QtWidgets.QLineEdit(self.centralwidget)
        self.Vend.setGeometry(QtCore.QRect(510, 270, 100, 30))
        self.Vend.setObjectName("Vend")
        self.Vstep = QtWidgets.QLineEdit(self.centralwidget)
        self.Vstep.setGeometry(QtCore.QRect(710, 270, 100, 30))
        self.Vstep.setObjectName("Vstep")
        self.Hend = QtWidgets.QLineEdit(self.centralwidget)
        self.Hend.setGeometry(QtCore.QRect(510, 230, 100, 30))
        self.Hend.setObjectName("Hend")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 230, 60, 30))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(630, 230, 60, 30))
        self.label_9.setObjectName("label_9")
        self.Hstep = QtWidgets.QLineEdit(self.centralwidget)
        self.Hstep.setGeometry(QtCore.QRect(710, 230, 100, 30))
        self.Hstep.setAutoFillBackground(False)
        self.Hstep.setObjectName("Hstep")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(630, 270, 60, 30))
        self.label_10.setObjectName("label_10")
        self.FileNam = QtWidgets.QLineEdit(self.centralwidget)
        self.FileNam.setGeometry(QtCore.QRect(120, 100, 150, 30))
        self.FileNam.setObjectName("FileNam")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 100, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(280, 100, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.ExpTim = QtWidgets.QLineEdit(self.centralwidget)
        self.ExpTim.setGeometry(QtCore.QRect(380, 100, 80, 30))
        self.ExpTim.setObjectName("ExpTim")
        self.StartScan = QtWidgets.QPushButton(self.centralwidget)
        self.StartScan.setGeometry(QtCore.QRect(20, 330, 100, 50))
        self.StartScan.setObjectName("StartScan")
        self.SelSt = QtWidgets.QPushButton(self.centralwidget)
        self.SelSt.setGeometry(QtCore.QRect(200, 190, 90, 30))
        self.SelSt.setObjectName("SelSt")
        self.SelEnd = QtWidgets.QPushButton(self.centralwidget)
        self.SelEnd.setGeometry(QtCore.QRect(410, 190, 90, 30))
        self.SelEnd.setObjectName("SelEnd")
        self.Newlog = QtWidgets.QPushButton(self.centralwidget)
        self.Newlog.setGeometry(QtCore.QRect(300, 340, 90, 30))
        self.Newlog.setObjectName("Newlog")
        self.SelPts = QtWidgets.QPushButton(self.centralwidget)
        self.SelPts.setGeometry(QtCore.QRect(410, 340, 90, 30))
        self.SelPts.setObjectName("SelPts")
        self.RunPts = QtWidgets.QPushButton(self.centralwidget)
        self.RunPts.setGeometry(QtCore.QRect(520, 340, 90, 30))
        self.RunPts.setObjectName("RunPts")
        self.Notes = QtWidgets.QLabel(self.centralwidget)
        self.Notes.setGeometry(QtCore.QRect(300, 300, 300, 30))
        self.Notes.setText("")
        self.Notes.setObjectName("Notes")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(480, 100, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.Phi = QtWidgets.QLineEdit(self.centralwidget)
        self.Phi.setGeometry(QtCore.QRect(560, 100, 80, 30))
        self.Phi.setObjectName("Phi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PX2 Grid Scan"))
        self.label_2.setText(_translate("MainWindow", "Linux Path"))
        self.label_3.setText(_translate("MainWindow", "Win Path"))
        self.Hmotor.setPlaceholderText(_translate("MainWindow", "eg. 13BMC:m46"))
        self.label.setText(_translate("MainWindow", "Hor motor"))
        self.Vmotor.setPlaceholderText(_translate("MainWindow", "eg. 13BMC:m??"))
        self.label_4.setText(_translate("MainWindow", "Ver motor"))
        self.label_5.setText(_translate("MainWindow", "Ver start"))
        self.label_6.setText(_translate("MainWindow", "Hor start"))
        self.label_7.setText(_translate("MainWindow", "Ver end"))
        self.Vstep.setPlaceholderText(_translate("MainWindow", ">=2"))
        self.label_8.setText(_translate("MainWindow", "Hor end"))
        self.label_9.setText(_translate("MainWindow", "Hor step"))
        self.Hstep.setPlaceholderText(_translate("MainWindow", ">=2"))
        self.label_10.setText(_translate("MainWindow", "Ver step"))
        self.label_11.setText(_translate("MainWindow", "File name"))
        self.label_12.setText(_translate("MainWindow", "Expotime/fr"))
        self.StartScan.setText(_translate("MainWindow", "Start scan"))
        self.SelSt.setText(_translate("MainWindow", "Select start"))
        self.SelEnd.setText(_translate("MainWindow", "Select end"))
        self.Newlog.setText(_translate("MainWindow", "New log"))
        self.SelPts.setText(_translate("MainWindow", "Select pts"))
        self.RunPts.setText(_translate("MainWindow", "Run pts"))
        self.label_13.setText(_translate("MainWindow", "Phi angle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
