#!/bin/sh
#
#  @(#)versionsave	6.1  05/11/20 CSS
#
#  "pyspec" Release 6
#

# Tag revisions like this:
# $ git tag -a -m "Version 0.2" v0.2 HEAD

VF=VERSION.py
VERSION_TEMPLATE="version_template.py"
DEFAULT_VERSION=UKNOWN

VT=`cat $VERSION_TEMPLATE`

# First see if there is a version file (included in release tarballs),
# then try git-describe, then default.
if test -d .git -o -f .git
then
    VN=$(git describe --abbrev=4 HEAD 2>/dev/null)
    case _"$VN" in
	      _) VN="$DEFAULT_VERSION"
		 ;;
	v[0-9]*)
		 git update-index -q --refresh
		 test -z "$(git diff-index --name-only HEAD --)" ||  VN="$VN-mod"
		 ;;
    esac
else
    VN="$DEFAULT_VERSION"
fi

VN=$(expr "$VN" : v*'\(.*\)')

# Show the version to the user via stderr
echo >&2 "$VN"

# Parse the existing VERSION
if test -r $VF
then
    VC=`python $VF`
else
    VC=unset
fi

# If version has changed, update VERSION
#test "$VN" = "$VC" || {
sed 's/"%s"/"'$VN'"/' < $VERSION_TEMPLATE >$VF
echo >&2 "($VF updated)"
#}
